networks:
  foodies-network:
    driver: bridge

services:
  template-service:
    build:
      context: ./services/_template
    container_name: template-service
    ports:
      - "8080:8080"
    networks:
      - foodies-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
